build: false

environment:
  PYTHONIOENCODING: "UTF-8"

  matrix:
    - PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "64"
      CONDA_PY: "37"
      CONDA_INSTALL_LOCN: "C:\\Miniconda37-x64"
      # JOB: "Python 3.7 64bit"
      # PYTHON: "C:\\Python37_64"
      # CONDA_ENV_PY: "3.7"

install:
  # - "powershell .\\ci\\appveyor\\install_miniconda.ps1"
  # - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
  - cmd: conda config --set always_yes yes --set changeps1 no
  - cmd: conda info
  - cmd: DIR
  - cmd: python --version
  - cmd: conda update conda
  - cmd: conda config --append channels conda-forge
  - cmd: conda config --append channels cmutel
  - cmd: conda config --append channels haasad
  - cmd: conda install conda-build
  - cmd: conda build .\\ci\\travis\\recipe
  - cmd: conda create -n test_env python=%CONDA_ENV_PY%
  - cmd: activate test_env
  - cmd: conda install --use-local activity-browser-dev
  - cmd: conda install -q "pytest<3.5" pytest-qt pytest-mock
#  - cmd: conda install pytest pytest-qt pytest-mock

#test_script:
  - pytest
#  - py.test



## modified from https://github.com/haasad/PyPardisoProject
#build: false
#
#environment:
#  matrix:
#    - JOB: "Python 3.7, 64bit"
#      PYTHON: "C:\\Python37_64"
#      PYTHON_VERSION: "3.7"
#      PYTHON_ARCH: "64"
#      CONDA_PY: "37"
#      CONDA_ENV_PY: "3.7"
#
#install:
#  - "powershell .\\ci\\appveyor\\install_miniconda.ps1"
#  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
#  - "conda info"
#  - "DIR"
#  - "conda update conda"
#  - "conda config --set always_yes yes --set changeps1 no"
#  - "conda config --append channels conda-forge"
#  - "conda config --append channels cmutel"
#  - "conda config --append channels haasad"
#  - "conda install conda-build"
#  - "conda build .\\ci\\travis\\recipe"
#  - "conda create -n test_env python=%CONDA_ENV_PY%"
#  - "activate test_env"
#  - "conda install --use-local activity-browser-dev"
#  - 'conda install -q "pytest<3.5" pytest-qt pytest-mock'
#
#test_script:
#  - "py.test"
